FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

RUN apt update && apt install -y curl wget

COPY out/amd64-cuda /app/onnxruntime-server
COPY download-onnxruntime.sh /app/onnxruntime-server/

WORKDIR /app/onnxruntime-server
RUN deploy/build-docker/download-onnxruntime.sh linux x64-gpu

CMD ["/app/onnxruntime-server/bin/onnxruntime-server"]
