//
// Created by Kibae Shin on 2023/08/30.
//

#ifndef ONNX_RUNTIME_SERVER_STANDALONE_HPP
#define ONNX_RUNTIME_SERVER_STANDALONE_HPP

class standalone {};

#endif // ONNX_RUNTIME_SERVER_STANDALONE_HPP
